# Source file from https://github.com/bytedance/gopkg/blob/develop/.github/workflows/feishu-notify.yml. Thanks to the original developers.
name: Feishu Notification

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  pr-opened:
    name: Pull Request Opened Notification
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Feishu Message
        env:
          ACTIONS_FEISHU_TAG: v1.3.1
          INPUT_WEBHOOK: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          INPUT_MESSAGE_TYPE: post
          INPUT_TITLE: üéâNew Pull Request
          INPUT_CONTENT: |
            @${{ github.event.pull_request.user.login }} opened pull request #${{ github.event.pull_request.number }}:

                ${{ github.event.pull_request.title }}

            ü´±See: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}.
        run: |
          sudo apt update
          sudo apt install wget -y
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu

  issues-opened:
    name: Issue Opened Notification
    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Feishu Message
        env:
          ACTIONS_FEISHU_TAG: v1.3.1
          INPUT_WEBHOOK: ${{ secrets.FEISHU_ROBOT_WEBHOOK_URL }}
          INPUT_MESSAGE_TYPE: post
          INPUT_TITLE: üêõNew Issue
          INPUT_CONTENT: |
            @${{ github.event.issue.user.login }} opened issue #${{ github.event.issue.number }}:

                ${{ github.event.issue.title }}

            ü´±See: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}.
        run: |
          sudo apt update
          sudo apt install wget -y
          wget -q https://github.com/xiachufang/actions-feishu/releases/download/${{ env.ACTIONS_FEISHU_TAG }}/linux-amd64-actions-feishu.tar.gz
          tar zxf linux-amd64-actions-feishu.tar.gz feishu
          ./feishu